# Duvet requirements traceability config for `sql` and `sql_derive`.
#
# Duvet doesn't like it when the specification is in a different directory from `.duvet`. Otherwise we would put this in the sql directory.

'$schema' = "https://awslabs.github.io/duvet/config/v0.4.0.json"

[[source]]
pattern = "sql/src/**/*.rs"

[[source]]
pattern = "sql_derive/src/**/*.rs"

[[specification]]
source = "traits/spec.md"

[report.html]
enabled = true

# Enable snapshots to prevent requirement coverage regressions
[report.snapshot]
enabled = true
path = ".duvet/sql_snapshot.txt"
