[package]
name = "storage_noodle_sql_derive"
rust-version = { workspace = true }
edition = { workspace = true }

[lib]
proc-macro = true

[dependencies]
proc-macro2 = { workspace = true }
syn = { workspace = true }
quote = { workspace = true }

[lints]
workspace = true
